# kubernetes in docker
brew "kind"

# k3d is k3s in docker
brew "k3d"

# kubernetes cli
brew "kubernetes-cli"

# k8s package manager
brew "helm"

# package manager installing kubectl plugins
brew "krew"

# k8s dashboard
brew "k9s"

# for Argo CD command line interface
brew "argocd"

# this is for bitwarden to work as your password manager
brew "bitwarden-cli"

# this is for managing cilium
brew "cilium-cli"

# this is for managing minio clients
brew "minio-mc"
