# kubernetes in docker
brew "kind"

# kubernetes cli
brew "kubernetes-cli"

# k8s package manager
brew "helm"

# package manager installing kubectl plugins
brew "krew"

# k8s dashboard
brew "k9s"

# for Argo CD command line interface
brew "argocd"

# this is for bitwarden to work as your password manager
brew "bitwarden-cli"
